apiVersion: v1
kind: ConfigMap
metadata:
  name: is-broker-events
  namespace: default
data:
  options: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "broker_management_api": {
        "uri": "http://guest:guest@rabbitmq.default",
        "max_retries": 10,
        "timeout": 5.0
      } 
    }
