apiVersion: apps/v1
kind: Deployment
metadata:
  name: is-broker-events
  namespace: default
spec:
  selector:
    matchLabels:
      app: is-broker-events
  replicas: 1
  template:
    metadata:
      labels:
        app: is-broker-events
    spec:
      containers:
      - name: service 
        image: labvisio/is-broker-events:0.1.0
        imagePullPolicy: Always
        command: ["is-broker-events"]
        args: ["/etc/is-broker-events/options.json"]
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        resources:
          limits: 
            cpu: "1.0"
            memory: 256Mi
        volumeMounts:
          - name: options
            mountPath: /etc/is-broker-events
      volumes:
      - name: options
        configMap:
          name: is-broker-events
          items:
          - key: options
            path: options.json
